name: build-and-deploy-site CI

on:
    push:
        branches: ['deployment']
    pull_request:
        branches: ['deployment']

jobs:
    build:
        runs-on: self-hosted

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: |
                  cd backend
                  npm ci
            - run: |
                  cd frontend
                  npm ci
                  npm run build
                  pm2 stop 1
                  pm2 start 1
                  pm2 save
                  sudo service nginx restart
            - run: |
                  npm install -g pm2
                  pm2 stop 0
                  pm2 start 0
                  pm2 save
                  sudo service nginx restart
